export const appHandoff = {
  id: 'app-handoff',
  title: 'WhatsApp → Sahulat App Handoff',
  subtitle: 'Seamless transition from chat to app for loyalty & vouchers',
  icon: '🔄',
  steps: [
    {
      id: 1,
      type: 'message',
      sender: 'bot',
      description: 'Oris starts order flow',
      content: "Let's build your order! 🛒\n\nWhat do you need today?",
    },
    {
      id: 2,
      type: 'message',
      sender: 'user',
      description: 'Retailer lists items',
      content: "Lay's Classic x5, Kurkure x3",
    },
    {
      id: 3,
      type: 'message',
      sender: 'bot',
      description: 'Oris shows cart summary',
      content: '🛒 Your cart:\n\n📦 5× Lay\'s Classic — PKR 6,000\n📦 3× Kurkure Chutney — PKR 2,700\n\n💰 Total: PKR 8,700',
    },
    {
      id: 4,
      type: 'message',
      sender: 'bot',
      description: 'Oris offers app handoff with benefits',
      content: 'Want to earn loyalty points and spin the Lucky Draw? 🎰\n\nComplete your order in the Sahulat App:\n\n✅ Apply voucher codes\n⭐ Earn 87 loyalty points\n🎡 Spin for prizes!',
      hasButton: true,
      buttonText: 'Open Sahulat App →',
      buttonAction: 'open-app',
    },
    {
      id: 5,
      type: 'transition',
      sender: 'system',
      description: 'Phone transitions to Sahulat App with pre-filled cart',
      content: {
        to: 'sahulat',
        cart: [
          { name: "Lay's Classic", qty: 5, price: 6000 },
          { name: 'Kurkure Chutney', qty: 3, price: 2700 },
        ],
        total: 8700,
        voucher: 'WELCOME10',
        loyaltyPoints: 2450,
        pendingPoints: 87,
      },
    },
    {
      id: 6,
      type: 'ui-action',
      sender: 'system',
      description: 'Voucher applied — 10% discount revealed',
      content: {
        action: 'apply-voucher',
        voucher: 'WELCOME10',
        discount: 870,
        newTotal: 7830,
        showLuckyWheel: true,
      },
    },
    {
      id: 7,
      type: 'ui-action',
      sender: 'system',
      description: '"Complete Order" button pulses to prompt action',
      content: {
        action: 'highlight-cta',
      },
    },
    {
      id: 8,
      type: 'ui-action',
      sender: 'system',
      description: 'Order confirmed — confetti celebration',
      content: {
        action: 'order-success',
        orderNumber: 'PKR-7844',
        delivery: 'Tomorrow, 9 AM - 11 AM',
        pointsEarned: 87,
        totalPoints: 2537,
      },
    },
  ],
}
