export const photoList = {
  id: 'photo-list',
  title: 'Photo List Ordering',
  subtitle: 'Retailer sends handwritten list — AI reads & matches products',
  icon: '📸',
  steps: [
    {
      id: 1,
      type: 'message',
      sender: 'bot',
      description: 'Oris prompts for photo',
      content: 'Hi! 👋\n\nSend me a photo of your shopping list and I\'ll process it instantly 📸\n\nHandwritten lists, typed notes — anything works!',
    },
    {
      id: 2,
      type: 'photo',
      sender: 'user',
      description: 'Retailer sends handwritten shopping list',
      content: {
        items: [
          "Lay's Masala × 10",
          'Kurkure × 5',
          'Bisconni Cocomo × 8',
          'Tapal Family Mix × 3',
        ],
      },
    },
    {
      id: 3,
      type: 'typing',
      sender: 'bot',
      description: 'Oris reading and analyzing the photo',
      content: null,
    },
    {
      id: 4,
      type: 'message',
      sender: 'bot',
      description: 'Oris matches products from the list',
      content: '📋 I\'ve read your list! Here\'s what I matched:\n\n1. Lay\'s Masala 🌶️ × 10 — PKR 12,000\n2. Kurkure Chutney × 5 — PKR 4,500\n3. Bisconni Cocomo × 8 — PKR 5,200\n4. Tapal Family Mix × 3 — PKR 2,100\n\n💰 Subtotal: PKR 23,800',
    },
    {
      id: 5,
      type: 'message',
      sender: 'bot',
      description: 'Oris offers upsell with promo',
      content: '🎉 Special offer!\n\nBuy 2+ packs of Aquafina and get 1 FREE. 💧\n\nWant to add some to your order?',
    },
    {
      id: 6,
      type: 'message',
      sender: 'user',
      description: 'Retailer says yes to Aquafina',
      content: 'ہاں 3 پیک ایکوافینا',
      isUrdu: true,
    },
    {
      id: 7,
      type: 'typing',
      sender: 'bot',
      description: 'Oris adding items',
      content: null,
    },
    {
      id: 8,
      type: 'message',
      sender: 'bot',
      description: 'Updated cart with Aquafina + promo',
      content: 'Added! ✅\n\n3× Aquafina 1.5L — PKR 1,080\n🎁 1× Aquafina FREE (saved PKR 360!)\n\n💰 **New Total: PKR 24,880**',
      hasButton: true,
      buttonText: 'Place Order ✓',
    },
    {
      id: 9,
      type: 'message',
      sender: 'bot',
      description: 'Order placed confirmation',
      content: 'Order placed! 🎉 #PKR-7843\n\n📅 Delivery: Tomorrow 2-4 PM\n💪 You saved PKR 360 with today\'s promo!\n\n⭐ +238 loyalty points earned!',
      isSuccess: true,
    },
  ],
}
