export const smartNotifications = {
  id: 'smart-notifications',
  title: 'Smart Notifications',
  subtitle: 'AI-powered proactive outreach — delivery, restock, promos & more',
  icon: '🔔',
  steps: [
    {
      id: 1,
      type: 'message',
      sender: 'bot',
      description: 'Delivery status update with tracking',
      content: '🚛 Order #PKR-7842 update:\n\n✅ Packed and dispatched!\n📍 Current: LTAB Distribution Hub, Lahore\n🕐 ETA: Today 2:00 - 4:00 PM',
      hasButton: true,
      buttonText: 'Track Delivery 📍',
      cardType: 'delivery',
    },
    {
      id: 2,
      type: 'message',
      sender: 'bot',
      description: 'AI restock suggestion based on ordering pattern',
      content: "📊 Smart Restock Alert!\n\nBased on your history, you reorder Lay's Classic every 14 days.\nIt's been 13 days since your last order. ⏰\n\n🔄 Your usual order:\n• Lay's Classic ×5\n• Tapal Danedar ×3\n\nShall I place this order?",
      hasButtons: true,
      buttons: ['Yes, reorder 🛒', 'Modify first ✏️'],
      cardType: 'restock',
    },
    {
      id: 3,
      type: 'rich-card',
      sender: 'bot',
      description: 'Weekly store performance card',
      content: {
        header: '📈 Weekly Store Performance',
        metrics: [
          { label: 'Orders', value: '12', change: '+20% vs last week', positive: true },
          { label: 'Revenue', value: 'PKR 45,000', change: '+15%', positive: true },
          { label: 'Top Seller', value: "Lay's Masala 🌶️", change: null, positive: null },
          { label: 'Trending', value: 'Kurkure Chutney ↗️', change: 'in your area', positive: true },
        ],
        tip: '💡 Tip: Consider increasing Bisconni stock for the upcoming school season',
      },
    },
    {
      id: 4,
      type: 'message',
      sender: 'bot',
      description: 'Festival promo — double loyalty points on Tapal',
      content: '🎊 FESTIVAL SPECIAL!\n\nDouble loyalty points on ALL Tapal products this week! ☕\n\n⭐ Tapal Danedar 950g — 170 pts (normally 85)\n⭐ Tapal Family Mix — 120 pts (normally 60)\n\nValid until Friday.',
      hasButton: true,
      buttonText: 'View All Promos 🎁',
      cardType: 'promo',
    },
    {
      id: 5,
      type: 'message',
      sender: 'bot',
      description: 'Payment due reminder with payment options',
      content: '💳 Payment Reminder\n\nYour invoice #INV-2847 of PKR 23,500 is due in 3 days.',
      hasButtons: true,
      buttons: ['Pay via JazzCash', 'Pay via EasyPaisa', 'Request Extension'],
      cardType: 'payment',
    },
    {
      id: 6,
      type: 'nps',
      sender: 'bot',
      description: 'Post-delivery NPS survey',
      content: 'How was your last delivery experience? Rate 1-5 ⭐',
      cardType: 'survey',
    },
  ],
}
