export const smartStoreVisit = {
  id: 'smart-store-visit',
  title: { en: 'Smart Store Visit', ur: 'سمارٹ اسٹور وزٹ' },
  subtitle: { en: 'AI guides the rep through planogram & cooler compliance checks', ur: 'AI نمائندے کو پلانوگرام اور کولر کمپلائنس چیک میں رہنمائی کرتا ہے' },
  icon: '🏪',
  isSeller: true,
  steps: [
    {
      id: 1,
      type: 'message',
      sender: 'bot',
      description: 'SalesMate confirms store arrival',
      content: {
        en: "📍 You've arrived at **Al-Farooq General Store**!\n\nLet's run a quick compliance check to maximize your visit. This takes 2 minutes. 🎯",
        ur: '📍 آپ **الفاروق جنرل اسٹور** پہنچ گئے!\n\nاپنا وزٹ بہترین بنانے کے لیے فوری کمپلائنس چیک کریں۔ اس میں 2 منٹ لگیں گے۔ 🎯',
      },
      hasButton: true,
      buttonText: { en: 'Start Check 📋', ur: 'چیک شروع کریں 📋' },
    },
    {
      id: 2,
      type: 'message',
      sender: 'user',
      description: 'Rep starts compliance check',
      content: { en: 'Start Check 📋', ur: 'چیک شروع کریں 📋' },
      isButton: true,
    },
    {
      id: 3,
      type: 'typing',
      sender: 'bot',
      description: 'SalesMate preparing camera instructions',
    },
    {
      id: 4,
      type: 'message',
      sender: 'bot',
      description: 'SalesMate asks for beverages cooler photo',
      content: {
        en: '📸 Please take a photo of the **beverages cooler** so AI can check planogram compliance.',
        ur: '📸 برائے کرم **مشروبات کولر** کی فوٹو لیں تاکہ AI پلانوگرام کمپلائنس چیک کر سکے۔',
      },
    },
    {
      id: 5,
      type: 'photo',
      sender: 'user',
      description: 'Rep uploads photo of beverages cooler',
      content: {
        mode: 'camera',
        label: { en: '📸 Beverages Cooler', ur: '📸 مشروبات کولر' },
        caption: { en: 'Al-Farooq General Store', ur: 'الفاروق جنرل اسٹور' },
      },
    },
    {
      id: 6,
      type: 'typing',
      sender: 'bot',
      description: 'AI analyzing planogram compliance',
    },
    {
      id: 7,
      type: 'rich-card',
      sender: 'bot',
      description: 'AI planogram compliance analysis with scores',
      content: {
        header: { en: '🤖 AI Planogram Analysis', ur: '🤖 AI پلانوگرام تجزیہ' },
        variant: 'ai',
        metrics: [
          { label: { en: 'Overall Score', ur: 'مجموعی اسکور' }, value: '74%', progress: 74, positive: true },
          { label: { en: 'Pepsi Cola', ur: 'پیپسی کولا' }, value: '60%', progress: 60, positive: false },
          { label: { en: "Lay's Snacks", ur: 'لیز سنیکس' }, value: '92%', progress: 92, positive: true },
          { label: { en: '7UP / Mirinda', ur: '7UP / مرنڈا' }, value: '85%', progress: 85, positive: true },
        ],
        tip: {
          en: '⚠️ Pepsi shelf gap detected — 3 facings missing. Suggest restocking now.',
          ur: '⚠️ پیپسی شیلف گیپ ملا — 3 فیسنگز غائب۔ ابھی ری اسٹاکنگ تجویز ہے۔',
        },
      },
    },
    {
      id: 8,
      type: 'typing',
      sender: 'bot',
      description: 'SalesMate preparing order recommendation',
    },
    {
      id: 9,
      type: 'message',
      sender: 'bot',
      description: 'AI recommends immediate order to fix compliance',
      content: {
        en: "Based on the analysis, here's what I recommend:\n\n✅ **Immediate Order:**\n• Pepsi Cola 1.5L ×4 cartons (fix shelf gap)\n• Pepsi Cola 500ml ×2 cartons\n\n💰 Order value: PKR 4,320\n🚚 Same-day delivery available",
        ur: 'تجزیے کی بنیاد پر، یہ سفارش ہے:\n\n✅ **فوری آرڈر:**\n• پیپسی کولا 1.5L ×4 کارٹن (شیلف گیپ ٹھیک کریں)\n• پیپسی کولا 500ml ×2 کارٹن\n\n💰 آرڈر قدر: PKR 4,320\n🚚 اسی دن ڈیلیوری دستیاب',
      },
      hasButton: true,
      buttonText: { en: 'Place Order 🛒', ur: 'آرڈر دیں 🛒' },
    },
    {
      id: 10,
      type: 'message',
      sender: 'user',
      description: 'Rep places the order',
      content: { en: 'Place Order 🛒', ur: 'آرڈر دیں 🛒' },
      isButton: true,
    },
    {
      id: 11,
      type: 'typing',
      sender: 'bot',
      description: 'SalesMate confirming order placement',
    },
    {
      id: 12,
      type: 'message',
      sender: 'bot',
      description: 'Order confirmed and visit completed',
      content: {
        en: "Order placed! ✅ #PKR-8901\n\n🚚 Delivery: Today 2–4 PM\n⭐ Visit score: 74% → 100% after delivery\n\n📍 Next stop: Ahmed Traders, 1.1 km →",
        ur: 'آرڈر دے دیا! ✅ #PKR-8901\n\n🚚 ڈیلیوری: آج دوپہر 2–4\n⭐ وزٹ اسکور: ڈیلیوری کے بعد 74% → 100%\n\n📍 اگلا اسٹور: احمد ٹریڈرز، 1.1 کلومیٹر →',
      },
      isSuccess: true,
    },
  ],
}
